execute pathogen#infect()
syntax on
filetype plugin indent on
set ruler
set hlsearch
let c_space_errors = 1
set cc=80
match ErrorMsg '\s\+$'
match ErrorMsg '\t'

set tabstop=2
set shiftwidth=2
set expandtab

command Clean %s/\s\+$//e

colorscheme molokai
